name: Canary Deploy
description: Opens PR with a canary deploy
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  version:
    description: Version to deploy
    required: true
  merchant:
    description: Which merchant to update
    required: true
  environment:
    description: Which environment to update
    required: true
  cluster:
    description: Name of the cluster to deploy to
    required: true
  token:
    description: The token to use to access the GitHub API
    required: true

runs:
  using: node20
  main: dist/index.js
